import React, { useEffect, useState } from "react";
import { LanguageContext } from "./LanguageContext";

const translations = {
  en: {
    home: "Home",
    genres: "Genres",
    myList: "My List",
    searchPlaceholder: "Titles, people, genres",
    allGenres: "All Genres",
    langEnglish: "English",
    langArabic: "العربية",
    theme: "Theme",
    darkMode: "Dark ",
    lightMode: "Light ",
    searchResults: "Search results for",
    searchByGenre: "Search by genre",
    category: "Category",
    enterName: "Type a movie name or choose a genre in the search bar.",
    searching: "Searching...",
    errorLoading: "Error loading results. Please try again.",
    noResults: "No results found. Try changing the name or genre.",
    play: "Play",
    moreInfo: "More Info",
    loading: "Loading...",
    blockbusterMovies: "Blockbuster Movies",
    onlyOnLuxFilm: "Only on LuxFilm",
    upcoming: "Upcoming",
    topPicksForYou: "Top Picks for You",
    joinLuxFilm: "Join LuxFilm",
    createAccount: "Create your account and start streaming",
    fullName: "Full Name",
    username: "Username",
    email: "Email Address",
    phone: "Phone (Optional)",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullNameRequired: "Full name is required",
    firstLastNameRequired: "Please enter your first and last name",
    usernamePattern:
      "Username can only contain letters, numbers, and underscores",
    passwordMin: "Password must be at least 8 characters",
    invalidInput: "Invalid input",
    validationFailed: "Validation failed",
    currentPasswordIncorrect: "Current password is incorrect",
    passwordUpdateFailed: "Password update failed",
    userFallback: "User",
    createAccountBtn: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign In",
    welcome: "Welcome to LuxFilm",
    signInTitle: "Sign In",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    loginBtn: "Login",
    forgotPassword: "Forgot Password?",
    myAccount: "My Account",
    logout: "Logout",
    myWishlist: "My Wishlist",
    wishlistEmpty: "Your wishlist is empty",
    wishlistEmptyHint:
      "Start exploring movies and add them to your wishlist by clicking the heart icon on any movie card.",
    movieSavedSingle: "movie saved",
    browseMovies: "Browse Movies",
    removeFromWishlist: "Remove from Wishlist",
    addToWishlist: "Add to Wishlist",
    movieDetails: "Details",
    rating: "Rating",
    releaseDate: "Release Date",
    overview: "Overview",
    cast: "Cast",
    director: "Director",
    duration: "Duration",
    genre: "Genre",
    clearAll: "Clear All",
    wishlistSaved: "added to wishlist!",
    wishlistRemoved: "removed from wishlist",
    wishlistCleared: "Wishlist cleared",
    accessDenied: "Access Denied",
    signInToViewAccountDetails:
      "You need to be signed in to view account details.",
    signOut: "Sign Out",
    signOutOfAccount: "Sign Out of Account",
    memberSince: "Member since",
    accountStatus: "Account status",
    activeStatus: "Active",
    profileDetails: "Profile Details",
    edit: "Edit",
    cancel: "Cancel",
    emailReadOnly: "Email (read-only)",
    saving: "Saving...",
    updating: "Updating...",
    noSavedMoviesYet: "No saved movies yet",
    browseMoviesLink: "Browse movies →",
    viewAll: "View all →",
    dangerZone: "Danger Zone",
    lastUpdatedUnknown: "•••••••••••• — last updated unknown",
    originalLanguage: "Original Language",
    production: "Production",
    status: "Status",
    episodes: "Episodes",
    becauseYouWatchedThis: "Because you watched this",
    noDescriptionAvailable: "No description available.",
    remove: "Remove",
    detailsButton: "Details",
    moviesSaved: "movies saved",
    loadingMovies: "Loading movies...",
    validationError: "Please fill empty fields correctly.",
    passwordRequired: "Password is required",
    invalidEmail: "Invalid email address",
    userNotFound: "User not found",
    accountSettings: "Account Settings",
    editProfile: "Edit Profile",
    changePassword: "Change Password",
    viewWatchlist: "View Watchlist",
    moviesSaved: "Movies Saved",
    accountCreated: "Account created successfully!",
    loginFailed: "Login failed. Please try again.",
    // New keys for Login page
    welcomeBack: "Welcome Back",
    signInToAccount: "Sign in to your LuxFilm account",
    rememberMe: "Remember me",
    forgotPasswordLink: "Forgot password?",
    signingIn: "Signing in...",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    // New keys for Register page
    creatingAccount: "Creating account...",
    // New keys for MovieDetails page
    description: "Description",
    match: "% Match",
    ultraHD: "Ultra HD 4K",
    // New keys for WishlistPage
    signInToAccessWishlist: "Sign in to access your Wishlist",
    wishlistDescription:
      "Keep track of all the movies you want to watch. Sign in to save and manage your personal wishlist.",
    // New keys for AccountPage
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    updateProfile: "Update Profile",
    profileUpdated: "Profile updated successfully!",
    passwordChanged: "Password changed successfully!",
    currentPasswordRequired: "Current password is required",
    newPasswordMin: "New password must be at least 8 characters",
    passwordsDoNotMatch: "Passwords do not match",
    enterFirstLastName: "Enter first and last name",
    usernameMin: "Username must be at least 3 characters",
    usernameRegex: "Only letters, numbers, underscores",
    phoneMin: "Phone must be at least 10 digits",
    phoneDigitsOnly: "Digits only",
    // Footer
    audioDescription: "Audio Description",
    investorRelations: "Investor Relations",
    legalNotices: "Legal Notices",
    helpCenter: "Help Center",
    jobs: "Jobs",
    cookiePreferences: "Cookie Preferences",
    giftCards: "Gift Cards",
    termsOfUse: "Terms of Use",
    corporateInformation: "Corporate Information",
    mediaCenter: "Media Center",
    privacy: "Privacy",
    contactUs: "Contact Us",
    movies: "Movies",
    removeFromWishlistTitle: "Remove from wishlist",
    addToWishlistTitle: "Add to wishlist",
  },
  ar: {
    home: "الرئيسية",
    genres: "الأنواع",
    myList: "المفضلة",
    searchPlaceholder: "ابحث باسم الفيلم أو النوع",
    allGenres: "كل الأنواع",
    langEnglish: "English",
    langArabic: "العربية",
    theme: "الثيم",
    darkMode:"مظلم",
    lightMode: " فاتح",
    searchResults: "نتائج البحث عن",
    searchByGenre: "بحث حسب النوع",
    category: "الفئة",
    enterName: "اكتب اسم فيلم أو اختر نوعًا في شريط البحث.",
    searching: "جارٍ البحث...",
    errorLoading: "حدث خطأ أثناء تحميل النتائج. حاول مرة أخرى.",
    noResults: "لم يتم العثور على نتائج. حاول تغييرات في الاسم أو النوع.",
    play: "تشغيل",
    moreInfo: "المزيد",
    loading: "جارٍ التحميل...",
    blockbusterMovies: "أفلام البلوكسوستر",
    onlyOnLuxFilm: "حصريًا على لوكس فيلم",
    upcoming: "قادمة",
    topPicksForYou: "أفضل التوصيات لك",
    joinLuxFilm: "انضم إلى لوكس فيلم",
    createAccount: "أنشئ حسابك وابدأ المشاهدة",
    fullName: "الاسم الكامل",
    username: "اسم المستخدم",
    email: "عنوان البريد الإلكتروني",
    phone: "رقم الهاتف (اختياري)",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    fullNameRequired: "الاسم الكامل مطلوب",
    firstLastNameRequired: "يرجى إدخال الاسم الأول والأخير",
    usernamePattern:
      "اسم المستخدم يمكن أن يحتوي فقط على حروف وأرقام وشرطات سفلية",
    passwordMin: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
    invalidInput: "إدخال غير صالح",
    validationFailed: "فشل التحقق من صحة البيانات",
    currentPasswordIncorrect: "كلمة المرور الحالية غير صحيحة",
    passwordUpdateFailed: "فشل تحديث كلمة المرور",
    userFallback: "مستخدم",
    createAccountBtn: "إنشاء حساب",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    signIn: "تسجيل الدخول",
    welcome: "مرحبا بك في لوكس فيلم",
    signInTitle: "تسجيل الدخول",
    dontHaveAccount: "ليس لديك حساب؟",
    signUp: "إنشاء حساب",
    loginBtn: "دخول",
    forgotPassword: "هل نسيت كلمة المرور؟",
    myAccount: "حسابي",
    logout: "تسجيل الخروج",
    myWishlist: "قائمتي المفضلة",
    wishlistEmpty: "قائمتك المفضلة فارغة",
    wishlistEmptyHint:
      "ابدأ استكشاف الأفلام وأضفها إلى قائمتك المفضلة بالنقر على أيقونة القلب على بطاقة الفيلم.",
    movieSavedSingle: "فيلم محفوظ",
    browseMovies: "تصفح الأفلام",
    removeFromWishlist: "إزالة من المفضلة",
    addToWishlist: "إضافة إلى المفضلة",
    movieDetails: "التفاصيل",
    rating: "التقييم",
    releaseDate: "تاريخ الإصدار",
    overview: "نظرة عامة",
    cast: "طاقم العمل",
    director: "المخرج",
    duration: "المدة",
    genre: "النوع",
    clearAll: "حذف الكل",
    wishlistSaved: "تمت إضافة الفيلم للمفضلة!",
    wishlistRemoved: "تمت إزالة الفيلم من المفضلة",
    wishlistCleared: "تم مسح قائمة المفضلة",
    accessDenied: "تم رفض الوصول",
    signInToViewAccountDetails: "يجب تسجيل الدخول لعرض تفاصيل الحساب.",
    signOut: "تسجيل الخروج",
    signOutOfAccount: "تسجيل الخروج من الحساب",
    memberSince: "عضو منذ",
    accountStatus: "حالة الحساب",
    activeStatus: "نشط",
    profileDetails: "تفاصيل الملف الشخصي",
    edit: "تعديل",
    cancel: "إلغاء",
    emailReadOnly: "البريد الإلكتروني (للقراءة فقط)",
    saving: "جارٍ الحفظ...",
    updating: "جارٍ التحديث...",
    noSavedMoviesYet: "لا توجد أفلام محفوظة بعد",
    browseMoviesLink: "تصفح الأفلام →",
    viewAll: "عرض الكل →",
    dangerZone: "منطقة الخطر",
    lastUpdatedUnknown: "•••••••••••• — آخر تحديث غير معروف",
    originalLanguage: "اللغة الأصلية",
    production: "الإنتاج",
    status: "الحالة",
    episodes: "الحلقات",
    becauseYouWatchedThis: "لأنك شاهدت هذا",
    noDescriptionAvailable: "لا توجد وصف متاح.",
    remove: "إزالة",
    detailsButton: "التفاصيل",
    moviesSaved: "أفلام محفوظة",
    loadingMovies: "جارٍ تحميل الأفلام...",
    validationError: "يرجى ملء جميع الحقول بشكل صحيح.",
    passwordRequired: "كلمة المرور مطلوبة",
    invalidEmail: "عنوان بريد إلكتروني غير صحيح",
    userNotFound: "المستخدم غير موجود",
    accountSettings: "إعدادات الحساب",
    editProfile: "تعديل الملف الشخصي",
    changePassword: "تغيير كلمة المرور",
    viewWatchlist: "عرض قائمة المشاهدة",
    moviesSaved: "الأفلام المحفوظة",
    accountCreated: "تم إنشاء الحساب بنجاح!",
    loginFailed: "فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.",
    // New keys for Login page
    welcomeBack: "مرحبا بعودتك",
    signInToAccount: "سجل الدخول إلى حساب لوكس فيلم الخاص بك",
    rememberMe: "تذكرني",
    forgotPasswordLink: "نسيت كلمة المرور؟",
    signingIn: "جارٍ تسجيل الدخول...",
    termsOfService: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
    // New keys for Register page
    creatingAccount: "جارٍ إنشاء الحساب...",
    // New keys for MovieDetails page
    description: "الوصف",
    match: "% تطابق",
    ultraHD: "ألترا HD 4K",
    // New keys for WishlistPage
    signInToAccessWishlist: "سجل الدخول للوصول إلى قائمتك المفضلة",
    wishlistDescription:
      "تابع جميع الأفلام التي تريد مشاهدتها. سجل الدخول لحفظ وإدارة قائمتك المفضلة الشخصية.",
    // New keys for AccountPage
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    updateProfile: "تحديث الملف الشخصي",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
    passwordChanged: "تم تغيير كلمة المرور بنجاح!",
    currentPasswordRequired: "كلمة المرور الحالية مطلوبة",
    newPasswordMin: "كلمة المرور الجديدة يجب أن تكون 8 أحرف على الأقل",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة",
    enterFirstLastName: "أدخل الاسم الأول والأخير",
    usernameMin: "اسم المستخدم يجب أن يكون 3 أحرف على الأقل",
    usernameRegex: "فقط الحروف والأرقام والشرطة السفلية",
    phoneMin: "رقم الهاتف يجب أن يكون 10 أرقام على الأقل",
    phoneDigitsOnly: "أرقام فقط",
    // Footer
    audioDescription: "وصف الصوت",
    investorRelations: "علاقات المستثمرين",
    legalNotices: "الإشعارات القانونية",
    helpCenter: "مركز المساعدة",
    jobs: "الوظائف",
    cookiePreferences: "تفضيلات ملفات تعريف الارتباط",
    giftCards: "بطاقات الهدايا",
    termsOfUse: "شروط الاستخدام",
    corporateInformation: "المعلومات الشركاتية",
    mediaCenter: "مركز الإعلام",
    privacy: "الخصوصية",
    contactUs: "اتصل بنا",
    movies: "الأفلام",
    removeFromWishlistTitle: "إزالة من قائمة المفضلة",
    addToWishlistTitle: "إضافة إلى قائمة المفضلة",
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    if (typeof window === "undefined") return "en";
    return localStorage.getItem("appLang") || "en";
  });

  useEffect(() => {
    localStorage.setItem("appLang", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
